spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: *
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
